MNT Fix broken constraint on .travis.yml
silverstripe/silverstripe-elemental-bannerblock pull request #73
Opened 2021-05-14 05:10 UTC by maxime-rainville

That constraint is broken. 

I've made it generic so it can install whatever is greater than or equal to 4.7

2021-05-14 08:56 UTC, dhensby commented
Builds still failing, looks like this equivalent fix is needed (to `.travils.yml`) https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/67

2021-05-16 05:21 UTC, maxime-rainville commented
Tried quoting the constraint. Let's see what travis think about that.

2021-05-17 02:06 UTC, emteknetnz requested changes
The recipe should be `"4.7.x-dev || "` - it's the [documented way](https://github.com/silverstripe/silverstripe-travis-shared#use-a-range-provsion-and-define-a-minimum-recipe-version-to-match-a-minimum-version-in-composerjson) to require a minimum version of a recipe

The installation issue is only with REQUIRE_EXTRA

2021-05-17 02:06 UTC, emteknetnz commented on .travis.yml
> +    - REQUIRE_RECIPE="^4.7"
This should stay as `"4.7.x-dev || "`

2021-05-17 02:11 UTC, emteknetnz commented
Build has been failing on this module for 4 months.  Likely it started after [this commit](https://github.com/silverstripe/silverstripe-travis-shared/commit/92913d736b3a9d40e61d42fdb533cf60f679d2ef) in travis-shared

We DO NOT want to change the quoting in travis-shared - I've had multiple issues before with this and the way it's done in travis-shared `$REQUIRE_EXTRA` instead of `"$REQUIRE_EXTRA"` is that way for a reason

2021-05-17 05:13 UTC, emteknetnz commented
Actually just saw Dan's comment about it being equivalent of https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/67 which is passing (expect for PHP8, which is pending elemental php8 support) - we should use that PR instead

2021-05-17 05:13 UTC, closed without merging