Add getSummaryData method to return String for summary section of Ele…
silverstripe/silverstripe-elemental-bannerblock pull request #8
Opened 2018-08-02 02:23 UTC by raissanorth

…mentEditor

Required for https://github.com/dnadesign/silverstripe-elemental/pull/284 to allow the required data - content summary - to be pulled in via GraphQL

Requires https://github.com/dnadesign/silverstripe-elemental/pull/313

2018-08-02 02:29 UTC, ScopeyNZ submitted a review, later dismissed

2018-08-02 02:29 UTC, ScopeyNZ commented on src/Block/BannerBlock.php
> +        $summaryData = [];
Because this extends `FileBlock` you can have `$summaryData = parent::getSummaryData()` and then delete the next 4 lines 🙂

2018-08-02 21:15 UTC, robbieaverill commented
Can you please add a `NEW` commit prefix?

2018-08-02 21:40 UTC, robbieaverill requested changes
Wait to merge until the elemental parent PR is

2018-08-12 23:04 UTC, robbieaverill approved these changes

2018-08-12 23:51 UTC, merged